### ISSUE TITLE
Validate against multiple data types

### ISSUE THREAD

**Issue by cassiars-pe** [ericb/ciri#11]
I am working with a schema where the `value` field is usually a string but can be a float or a datetime object. Right now, I can only define the field with one data type, unless I create a custom field. Would it be possible to set multiple data types as valid for a particular field in a class?

**Comment by ericb** [comment]
Great idea. I've added two new field types in the latest release (0.6.0) that address this. The first is the
`Any` field which takes a sequence of fields to test against (in order). The second is the `Anything` field which is just a passthrough for values.

Cheers :beers:
